branches:
  only:
     - "master"
  
language: 
   - "scala"

scala: 
   - "2.12.6"

jdk: 
   - "oraclejdk10"

env:
   global:
      - BUILDRESULTS=$HOME/buildresults

cache:
    directories:
       - "$HOME/.m2/*"
       - "$HOME/.ivy2/*"
       
addons:
  apt:
    sources: ppa:cwchien/gradle
    packages: gradle-4.7
    
before_install:
   - echo Entering \'before_install\' step
   - mkdir -pv $BUILDRESULTS
   - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -


install:
   - echo Entering \'install\' step
   - sudo apt-get install -y nodejs
   
before_script:
   - echo Entering \'before_script\' step
   
script:
   - echo Entering \'script\' step

before_cache:
   - echo Entering \'before_cache\' step

after_success:
   - echo Entering \'after_success\' step

before_deploy:
   - echo Entering \'before_deploy\' step

deploy:
  - skip_cleanup: true
  - provider: script
  - script: echo Entering \'deploy\' step

after_deploy:
   - echo Entering \'after_deploy\' step

after_script:
   - echo Entering \'after_script\' step

 
notifications:
   email: "martin.rehwald@gmail.com"
